---
output: github_document
---

<!-- index.md is generated from index.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

# IPACS

## How do I run the model?
An explanation of how to install the package and run the model is available on the article ["How to run the IPACS model"](https://amyheather.github.io/ipacs/articles/how_to_run_the_ipacs_model.html).

## Function documentation
To view function documentation, go to the [function reference](https://amyheather.github.io/ipacs/reference/index.html) page.

## Link to github repo
To view the GitHub repo for this package, visit [https://github.com/amyheather](https://github.com/amyheather)

This repository contains models from the project "Improving Patient flow 
between Acute, Community and Social care (IPACS)", converted into a package
format. These are models used for D2A resource planning.  

**How does this repository differ from other repositories?**
This repository is based on [IPACS_MODEL](https://github.com/AliHarp/IPACS_MODEL) which contains the IPACS model with re-coding, comments, bug identification and bug fixes by [Amy Heather](https://github.com/amyheather). In this repository, the model is then converted into package format by [Amy Heather](https://github.com/amyheather).

For an explanation on how to run the model, [view the GitHub pages site](amyheather.github.io/ipacs/).

## Installation

You can install the development version of ipacs from GitHub with:

``` r
# install.packages("devtools")
# library("devtools")
devtools::install_github("amyheather/ipacs")
```
